INSERT INTO products (sku, name, brand, category, stage, price_cents, unit, per_unit, badge, details, is_hire, image_key, stock, active) VALUES
('NAP-NB-048', 'Cloud cotton nappies', 'Franklin''s essentials', 'Nappies & wipes', 'Newborn', 1750, '48 pack · size 1', '36p each', 'Most loved', 'Soft, breathable nappies for the earliest days. Choose the right size for your baby and keep a spare pack ready.', 0, 'img_seed_nappies.png', 40, 1),
('WIP-SNS-072', 'Pure care baby wipes', 'Franklin''s essentials', 'Nappies & wipes', 'All stages', 325, '72 wipes', '5p each', NULL, 'Gentle everyday wipes. Check the full ingredient list before use.', 0, 'img_seed_wipes.png', 60, 1),
('FML-ORG-800', 'Organic first milk', 'Little Meadow', 'Feeding', 'Newborn', 1600, '800g tin', '£2.00 per 100g', NULL, 'Infant formula. Always follow the manufacturer''s preparation and storage instructions. The pack information must be verified before sale.', 0, 'img_seed_milk.png', 25, 1),
('SNK-OAT-006', 'Oaty little bites', 'Tiny Table', 'Food & snacks', 'Toddler', 480, '6 snack packs', '80p per pack', 'Top up favourite', 'A handy snack for growing explorers. Ingredients and allergen information must be checked on the final product packaging.', 0, 'img_seed_snacks.png', 50, 1),
('CLT-SLP-03M', 'Everyday sleepsuit', 'Soft Days', 'Clothing & shoes', 'Infant', 2400, '0 to 3 months · blue', '£24 each', NULL, 'A soft cotton layer for naptime, playtime and everything in between.', 0, 'img_seed_sleepsuit.png', 15, 1),
('SHO-FST-05', 'First steps shoes', 'Soft Days', 'Clothing & shoes', 'Toddler', 2900, 'size 5 · butter', '£29 per pair', NULL, 'Flexible little shoes for early adventures. Check fit before purchasing.', 0, 'img_seed_shoes.png', 12, 1),
('CAR-STG-001', 'All-stage car seat', 'Franklin''s collection', 'Prams & car seats', 'Infant', 3900, 'per month', 'From £39/month', 'Hire it', 'Monthly hire shown for demonstration. Every physical seat would be individually tracked, inspected and supplied with fitting guidance.', 1, 'img_seed_carseat.png', 4, 1),
('PRM-CTY-001', 'The city pram', 'Franklin''s collection', 'Prams & car seats', 'Newborn', 5900, 'per month', 'From £59/month', 'Hire it', 'A compact pram on a flexible monthly hire plan. Availability and return terms are confirmed before a real booking.', 1, 'img_seed_pram.png', 3, 1),
('NAP-TD-040', 'Moving days nappies', 'Franklin''s essentials', 'Nappies & wipes', 'Toddler', 1900, '40 pack · size 5', '48p each', NULL, 'Everyday nappies for little ones on the move.', 0, 'img_seed_nappies.png', 35, 1),
('SNK-FRT-004', 'Fruit pouch selection', 'Tiny Table', 'Food & snacks', 'Infant', 520, '4 x 90g', '£1.44 per 100g', NULL, 'A selection of fruit pouches. Check age guidance, ingredients and allergens on packaging.', 0, 'img_seed_snacks.png', 45, 1),
('CLT-SLP-12M', 'Everyday sleepsuit', 'Soft Days', 'Clothing & shoes', 'Infant', 2600, '9 to 12 months · blue', '£26 each', NULL, 'Soft cotton layers in the next size up.', 0, 'img_seed_sleepsuit.png', 15, 1),
('WIP-BND-288', 'Wipes stock-up bundle', 'Franklin''s essentials', 'Nappies & wipes', 'All stages', 1100, '4 x 72 wipes', '4p each', 'Better value', 'A handy four-pack to keep the changing table stocked.', 0, 'img_seed_wipes.png', 30, 1);
