"use client";
import {useEffect,useMemo,useState} from "react";
import {ScrollRibbon} from "@/components/scroll-ribbon";
import {Search,ShoppingBasket,Heart,MapPin,ArrowRight,ChevronDown,Plus,Minus,CalendarDays,PackageCheck,SlidersHorizontal,X,Menu,Clock3,ShieldCheck,RotateCcw} from "lucide-react";
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from "@/components/ui/sheet";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";

type Item={id:number;sku:string;name:string;brand:string;category:string;stage:string;price:number;unit:string;perUnit:string;tile:number;badge?:string;details:string;isHire?:boolean};
const items:Item[]=[
 {id:1,sku:"NAP-NB-048",name:"Cloud cotton nappies",brand:"Franklin's essentials",category:"Nappies & wipes",stage:"Newborn",price:17.5,unit:"48 pack · size 1",perUnit:"36p each",tile:0,badge:"Most loved",details:"Soft, breathable nappies for the earliest days. Choose the right size for your baby and keep a spare pack ready."},
 {id:2,sku:"WIP-SNS-072",name:"Pure care baby wipes",brand:"Franklin's essentials",category:"Nappies & wipes",stage:"All stages",price:3.25,unit:"72 wipes",perUnit:"5p each",tile:1,details:"Gentle everyday wipes. Check the full ingredient list before use."},
 {id:3,sku:"FML-ORG-800",name:"Organic first milk",brand:"Little Meadow",category:"Feeding",stage:"Newborn",price:16,unit:"800g tin",perUnit:"£2.00 per 100g",tile:2,details:"Infant formula. Always follow the manufacturer's preparation and storage instructions. The pack information must be verified before sale."},
 {id:4,sku:"SNK-OAT-006",name:"Oaty little bites",brand:"Tiny Table",category:"Food & snacks",stage:"Toddler",price:4.8,unit:"6 snack packs",perUnit:"80p per pack",tile:3,badge:"Top up favourite",details:"A handy snack for growing explorers. Ingredients and allergen information must be checked on the final product packaging."},
 {id:5,sku:"CLT-SLP-03M",name:"Everyday sleepsuit",brand:"Soft Days",category:"Clothing & shoes",stage:"Infant",price:24,unit:"0–3 months · blue",perUnit:"£24 each",tile:4,details:"A soft cotton layer for naptime, playtime and everything in between."},
 {id:6,sku:"SHO-FST-05",name:"First steps shoes",brand:"Soft Days",category:"Clothing & shoes",stage:"Toddler",price:29,unit:"size 5 · butter",perUnit:"£29 per pair",tile:5,details:"Flexible little shoes for early adventures. Check fit before purchasing."},
 {id:7,sku:"CAR-STG-001",name:"All-stage car seat",brand:"Franklin's collection",category:"Prams & car seats",stage:"Infant",price:39,unit:"per month",perUnit:"From £39/month",tile:6,badge:"Hire it",details:"Monthly hire shown for demonstration. Every physical seat would be individually tracked, inspected and supplied with fitting guidance.",isHire:true},
 {id:8,sku:"PRM-CTY-001",name:"The city pram",brand:"Franklin's collection",category:"Prams & car seats",stage:"Newborn",price:59,unit:"per month",perUnit:"From £59/month",tile:7,badge:"Hire it",details:"A compact pram on a flexible monthly hire plan. Availability and return terms are confirmed before a real booking.",isHire:true},
 {id:9,sku:"NAP-TD-040",name:"Moving days nappies",brand:"Franklin's essentials",category:"Nappies & wipes",stage:"Toddler",price:19,unit:"40 pack · size 5",perUnit:"48p each",tile:0,details:"Everyday nappies for little ones on the move."},
 {id:10,sku:"SNK-FRT-004",name:"Fruit pouch selection",brand:"Tiny Table",category:"Food & snacks",stage:"Infant",price:5.2,unit:"4 x 90g",perUnit:"£1.44 per 100g",tile:3,details:"A selection of fruit pouches. Check age guidance, ingredients and allergens on packaging."},
 {id:11,sku:"CLT-SLP-12M",name:"Everyday sleepsuit",brand:"Soft Days",category:"Clothing & shoes",stage:"Infant",price:26,unit:"9–12 months · blue",perUnit:"£26 each",tile:4,details:"Soft cotton layers in the next size up."},
 {id:12,sku:"WIP-BND-288",name:"Wipes stock-up bundle",brand:"Franklin's essentials",category:"Nappies & wipes",stage:"All stages",price:11,unit:"4 x 72 wipes",perUnit:"4p each",tile:1,badge:"Better value",details:"A handy four-pack to keep the changing table stocked."}
];
type Line={id:number;mode:"once"|"repeat"|"hire";quantity:number;weeks:number;months:number;startDate?:string};
const money=(n:number)=>`£${n.toFixed(2)}`;
const categories=["All","Nappies & wipes","Feeding","Food & snacks","Clothing & shoes","Prams & car seats"];
const stageChoices=["All stages","Newborn","Infant","Toddler"];
const slots=["Tomorrow · 9–12","Tomorrow · 14–17","Friday · 10–13","Saturday · 9–12"];
function ProductImage({tile,name}:{tile:number;name:string}){return <div className="product-image" role="img" aria-label={name} style={{backgroundImage:`url('${import.meta.env.BASE_URL}catalogue.png')`,backgroundSize:"400% 200%",backgroundPosition:`${tile%4*100/3}% ${Math.floor(tile/4)*100}%`}}/>}
export default function Home(){
 const[section,setSection]=useState<"shop"|"repeat"|"hire"|"account">("shop");const[category,setCategory]=useState("All");const[stage,setStage]=useState("All stages");const[query,setQuery]=useState("");const[sort,setSort]=useState("Recommended");
 const[favourites,setFavourites]=useState<number[]>([]);const[lines,setLines]=useState<Line[]>([]);const[product,setProduct]=useState<Item|null>(null);const[mode,setMode]=useState<Line["mode"]>("once");const[weeks,setWeeks]=useState(4);const[months,setMonths]=useState(3);const[bagOpen,setBagOpen]=useState(false);const[checkoutOpen,setCheckoutOpen]=useState(false);const[postcode,setPostcode]=useState("");const[checkedPostcode,setCheckedPostcode]=useState("");const[slot,setSlot]=useState("");const[orderPlaced,setOrderPlaced]=useState(false);const[skipNext,setSkipNext]=useState(false);const[repeatPaused,setRepeatPaused]=useState(false);const[repeatWeeks,setRepeatWeeks]=useState(4);const[repeatBox,setRepeatBox]=useState([{id:1,quantity:2},{id:2,quantity:1}]);const[hireStart,setHireStart]=useState("");const[toast,setToast]=useState("");const[headerVisible,setHeaderVisible]=useState(true);const[menuOpen,setMenuOpen]=useState(false);
 const matching=useMemo(()=>{const a=items.filter(p=>(category==="All"||p.category===category)&&(stage==="All stages"||p.stage==="All stages"||p.stage===stage)&&(!query||`${p.name} ${p.brand} ${p.sku} ${p.category}`.toLowerCase().includes(query.toLowerCase()))&&(section!=="hire"||p.isHire));return [...a].sort((x,y)=>sort==="Price: low to high"?x.price-y.price:sort==="Price: high to low"?y.price-x.price:x.id-y.id)},[category,stage,query,sort,section]);
 const count=lines.reduce((n,x)=>n+x.quantity,0);const total=lines.reduce((n,x)=>n+items.find(p=>p.id===x.id)!.price*x.quantity,0);
 function selectSection(s:typeof section){setMenuOpen(false);setHeaderVisible(true);setSection(s);setCategory(s==="hire"?"Prams & car seats":"All");setStage("All stages");setQuery("");window.scrollTo({top:0,behavior:"smooth"})}
 function openItem(p:Item){setProduct(p);setMode(p.isHire?"hire":"once");setWeeks(4);setMonths(3);setHireStart("")}
 function add(p:Item,m:Line["mode"]=mode){const w=m==="repeat"?weeks:0;const term=m==="hire"?months:0;setLines(old=>{const i=old.findIndex(x=>x.id===p.id&&x.mode===m&&x.weeks===w&&x.months===term&&x.startDate===(m==="hire"?hireStart:undefined));return i<0?[...old,{id:p.id,mode:m,quantity:1,weeks:w,months:term,startDate:m==="hire"?hireStart:undefined}]:old.map((x,j)=>i===j?{...x,quantity:x.quantity+1}:x)});setProduct(null);if(m==="repeat")setRepeatBox(old=>{const existing=old.find(x=>x.id===p.id);return existing?old.map(x=>x.id===p.id?{...x,quantity:x.quantity+1}:x):[...old,{id:p.id,quantity:1}]});setToast(`${p.name} added to your basket`)}
 function change(index:number,delta:number){setLines(old=>old.map((x,i)=>i===index?{...x,quantity:x.quantity+delta}:x).filter(x=>x.quantity>0))}
 function changeRepeat(id:number,delta:number){setRepeatBox(old=>old.map(x=>x.id===id?{...x,quantity:x.quantity+delta}:x).filter(x=>x.quantity>0))}
 function toggleFavourite(id:number){setFavourites(old=>old.includes(id)?old.filter(x=>x!==id):[...old,id])}
 function checkPostcode(){if(!/^[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}$/i.test(postcode.trim())){setToast("Enter a valid UK postcode to preview delivery slots.");return}setCheckedPostcode(postcode.trim().toUpperCase());setToast("Sample slots shown. Live coverage and capacity are not connected.")}
 useEffect(()=>{let previous=window.scrollY;const onScroll=()=>{const current=window.scrollY;const delta=current-previous;if(current<80){setHeaderVisible(true);previous=current;return}if(Math.abs(delta)<8)return;previous=current;if(delta>0){if(!menuOpen&&!bagOpen&&!checkoutOpen&&!product)setHeaderVisible(false);setMenuOpen(false)}else setHeaderVisible(true)};window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[menuOpen,bagOpen,checkoutOpen,product]);

 useEffect(()=>{if(!menuOpen)return;const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape")setMenuOpen(false)};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[menuOpen]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:object,options:{signal:AbortSignal})=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:"filter_baby_catalogue",title:"Filter baby catalogue",description:"Filter the visible baby supplies catalogue by category and stage.",inputSchema:{type:"object",properties:{category:{type:"string",enum:categories},stage:{type:"string",enum:stageChoices}},required:["category","stage"],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const v=input as {category:string;stage:string};if(!categories.includes(v.category)||!stageChoices.includes(v.stage))throw Error("Invalid filter");setSection("shop");setCategory(v.category);setStage(v.stage);return {category:v.category,stage:v.stage,matches:items.filter(p=>(v.category==="All"||p.category===v.category)&&(v.stage==="All stages"||p.stage==="All stages"||p.stage===v.stage)).length}}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort()},[]);
 return <div className="tuck-app"><ScrollRibbon/><div className="demo-ribbon">CONCEPT PREVIEW <span>·</span> Illustrative products, slots and prices. No live orders or payments.</div><header className={`site-header ${headerVisible?"":"header-hidden"}`}><button className="wordmark" onClick={()=>selectSection("shop")} aria-label="Franklin's Baby Supplies home"><span className="wordmark-icon">f<span>·</span></span><span>Franklin's <span className="wordmark-sub">Baby Supplies</span></span></button><nav id="primary-navigation" className={menuOpen?"nav-open":""} aria-label="Main"><button className={section==="shop"?"nav-active":""} onClick={()=>selectSection("shop")}>Shop all</button><button className={section==="repeat"?"nav-active":""} onClick={()=>selectSection("repeat")}>Repeat & top up</button><button className={section==="hire"?"nav-active":""} onClick={()=>selectSection("hire")}>Loved for a little while</button><button className={section==="account"?"nav-active":""} onClick={()=>selectSection("account")}>My deliveries</button></nav><div className="header-actions"><button className="menu-toggle" onClick={()=>{setMenuOpen(value=>!value);setHeaderVisible(true)}} aria-label={menuOpen?"Close menu":"Open menu"} aria-controls="primary-navigation" aria-expanded={menuOpen}>{menuOpen?<X size={23}/>:<Menu size={23}/>}</button><button onClick={()=>selectSection("account")} aria-label="Favourites"><Heart size={19}/><span className="mini-count">{favourites.length}</span></button><button className="basket-button" onClick={()=>setBagOpen(true)} aria-label={`Basket, ${count} items`}><ShoppingBasket size={19}/><span>Basket</span><b>{count}</b></button></div></header>
 <div className="utility-bar"><div><MapPin size={16}/>{checkedPostcode?<span>Delivery preview for <b>{checkedPostcode}</b></span>:<span>See delivery options near you</span>}<button onClick={()=>document.getElementById("delivery")?.scrollIntoView({behavior:"smooth"})}>Check postcode <ArrowRight size={14}/></button></div><span>Fresh little essentials, right on time.</span></div>
 <main>
 {section==="shop"&&<><section className="hero editorial-hero" aria-label="Franklin's baby supplies collection"><div className="hero-scenes" aria-hidden="true"><div className="hero-scene hero-scene-everyday"/><div className="hero-scene hero-scene-loved"/></div><div className="hero-content"><p className="kicker">THE EVERYDAY, BEAUTIFULLY TAKEN CARE OF</p><h1>Small things.<br/><i>Big relief.</i></h1><p>All their little essentials, delivered when you need them. Beautiful bigger things to love for a little while.</p><div className="hero-actions"><button onClick={()=>document.getElementById("catalogue")?.scrollIntoView({behavior:"smooth"})}>Shop baby essentials <ArrowRight size={18}/></button><button onClick={()=>selectSection("hire")}>Loved for a little while <ArrowRight size={17}/></button></div></div><div className="hero-footer"><span>FROM THE FIRST DAYS TO THE NEXT CHAPTER</span></div></section><div className="journey-strip"><button onClick={()=>{setCategory("All");document.getElementById("catalogue")?.scrollIntoView({behavior:"smooth"})}}><span>01</span><b>Shop once</b><small>Get what you need today</small><ArrowRight/></button><button onClick={()=>selectSection("repeat")}><span>02</span><b>Keep it coming</b><small>Your regulars, on repeat</small><ArrowRight/></button><button onClick={()=>selectSection("hire")}><span>03</span><b>Loved for a little while</b><small>Beautiful pieces for this stage</small><ArrowRight/></button></div></>}
 {section==="repeat"&&<section className="section-hero repeat-hero"><span className="kicker">THE EASY ROUTINE</span><h1>Running low?<br/><i>Not on our watch.</i></h1><p>Put the everyday essentials on a schedule, check the next box and add a little extra whenever you need it.</p><button onClick={()=>document.getElementById("catalogue")?.scrollIntoView({behavior:"smooth"})}>Build a repeat box <ArrowRight size={18}/></button></section>}
 {section==="hire"&&<section className="section-hero hire-hero"><span className="kicker">LOVED FOR A LITTLE WHILE</span><h1>Big things.<br/><i>For this stage.</i></h1><p>Choose a pram or car seat for this stage. See the monthly plan, condition and return terms before you commit.</p><button onClick={()=>document.getElementById("catalogue")?.scrollIntoView({behavior:"smooth"})}>Explore the collection <ArrowRight size={18}/></button></section>}
 {section==="account"?<section className="account-page"><div className="account-heading"><p className="kicker">YOUR ROUTINE</p><h1>My deliveries.</h1><p>A sample account view for the next delivery, quick top ups and favourites.</p></div><div className="account-grid"><article className="next-card"><div className="card-heading"><span><CalendarDays size={19}/> NEXT REPEAT DELIVERY</span><b>DEMO</b></div><h2>{repeatPaused?"Repeat plan paused":skipNext?"Next box skipped":"Your little-days box"}</h2><p>{repeatPaused?"Resume your sample plan when ready.":skipNext?"The next sample delivery has been skipped.":"Sample window: Friday, 10–13. Change cut-off: Thursday at 18:00."}</p><label className="repeat-cadence">Repeat every <select value={repeatWeeks} onChange={e=>setRepeatWeeks(Number(e.target.value))}><option value={2}>2 weeks</option><option value={4}>4 weeks</option><option value={6}>6 weeks</option></select></label><div className="box-list">{repeatBox.length?repeatBox.map(x=>{const item=items.find(p=>p.id===x.id)!;return <span key={x.id}>{item.name}<span className="repeat-controls"><button onClick={()=>changeRepeat(x.id,-1)} aria-label={`Remove one ${item.name}`}><Minus size={14}/></button><b>× {x.quantity}</b><button onClick={()=>changeRepeat(x.id,1)} aria-label={`Add one ${item.name}`}><Plus size={14}/></button></span></span>}):<span>Your repeat box is empty. Add an essential from the shop.</span>}</div><div className="card-actions"><button onClick={()=>{setSkipNext(!skipNext);setToast(skipNext?"Sample delivery resumed.":"Sample delivery skipped.")}}>{skipNext?"Resume delivery":"Skip this box"}</button><button onClick={()=>{setRepeatPaused(!repeatPaused);setToast(repeatPaused?"Sample plan resumed.":"Sample plan paused.")}}>{repeatPaused?"Resume plan":"Pause plan"}</button><button onClick={()=>selectSection("repeat")}>Add to repeat box ↗</button></div></article><article className="favourites-card"><div className="card-heading"><span><Heart size={19}/> YOUR FAVOURITES</span></div>{favourites.length?favourites.map(id=>{const p=items.find(x=>x.id===id)!;return <div className="fav-row" key={id}><ProductImage tile={p.tile} name={p.name}/><div><b>{p.name}</b><small>{p.unit}</small></div><button onClick={()=>add(p,p.isHire?"hire":"once")}>Add +</button></div>}):<p>Tap the heart on a product to keep it close for next time.</p>}</article></div><div className="account-foot"><div><RotateCcw size={25}/><h3>Last shop</h3><p>Want the regulars again? Rebuild a sample basket in one click.</p><button onClick={()=>{setLines([{id:1,mode:"once",quantity:2,weeks:0,months:0},{id:2,mode:"once",quantity:1,weeks:0,months:0}]);setBagOpen(true)}}>Rebuild last shop <ArrowRight size={17}/></button></div><div><ShieldCheck size={25}/><h3>Hire dashboard</h3><p>When connected, this is where return dates, inspections and exchanges will live.</p><button onClick={()=>selectSection("hire")}>Explore the collection <ArrowRight size={17}/></button></div></div></section>:<>
 {section==="repeat"&&<div className="benefit-line"><span><CalendarDays size={18}/> Every 2, 4 or 6 weeks</span><span><PackageCheck size={18}/> Top up between deliveries</span><span><Clock3 size={18}/> Skip before cut-off</span></div>}
 {section==="hire"&&<div className="benefit-line"><span><CalendarDays size={18}/> Choose a hire term</span><span><ShieldCheck size={18}/> Individual asset checks</span><span><RotateCcw size={18}/> Return when ready</span></div>}
 <section className="catalogue" id="catalogue"><div className="catalogue-heading"><div><p className="kicker">THE FRANKLIN'S EDIT</p><h2>{section==="hire"?"Made to move with you.":section==="repeat"?"Your everyday line-up.":"Everything for their next little chapter."}</h2><p>Browse the sample range and find the right size, pack or plan.</p></div><div className="result-count">{matching.length} products</div></div><div className="category-nav" role="group" aria-label="Product category">{categories.map(c=><button key={c} className={category===c?"selected":""} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="catalogue-tools"><label className="catalogue-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search nappies, snacks, shoes…" aria-label="Search products"/></label><div><label><SlidersHorizontal size={17}/> Stage <select value={stage} onChange={e=>setStage(e.target.value)}>{stageChoices.map(x=><option key={x}>{x}</option>)}</select></label><label>Sort <select value={sort} onChange={e=>setSort(e.target.value)}><option>Recommended</option><option>Price: low to high</option><option>Price: high to low</option></select></label></div></div><div className="product-grid">{matching.map(p=><article className="product-card" key={p.id}><div className={`image-wrap image-tone-${p.tile%4}`}><button onClick={()=>openItem(p)} className="image-button" aria-label={`View ${p.name}`}><ProductImage tile={p.tile} name={p.name}/></button>{p.badge&&<span className="pill">{p.badge}</span>}<button className={favourites.includes(p.id)?"heart saved":"heart"} onClick={()=>toggleFavourite(p.id)} aria-label={favourites.includes(p.id)?`Remove ${p.name} from favourites`:`Save ${p.name} to favourites`}><Heart size={19} fill={favourites.includes(p.id)?"currentColor":"none"}/></button></div><div className="product-details"><small>{p.brand} · {p.stage}</small><button onClick={()=>openItem(p)}>{p.name}</button><p>{p.unit} <span>·</span> {p.sku}</p><div className="product-price"><strong>{money(p.price)}</strong><span>{p.perUnit}</span></div><button className="card-add" onClick={()=>p.isHire?openItem(p):add(p,section==="repeat"?"repeat":"once")}>{p.isHire?"View hire plan":section==="repeat"?"Set to repeat":"Add to basket"} <Plus size={18}/></button></div></article>)}</div>{!matching.length&&<div className="no-results"><h3>Nothing quite like that.</h3><p>Try another category or clear your search.</p><button onClick={()=>{setQuery("");setCategory("All");setStage("All stages")}}>Show all products</button></div>}</section>
 <section className="delivery-section" id="delivery"><div><p className="kicker">GOOD TIMING IS EVERYTHING</p><h2>Delivery that fits<br/><i>real life.</i></h2><p>Preview how postcode checks and bookable windows would work. Live delivery coverage and capacity will connect to the fulfilment system.</p></div><div className="delivery-box"><label htmlFor="postcode">Enter your postcode</label><div className="postcode-row"><input id="postcode" placeholder="e.g. BR3 1AA" value={postcode} onChange={e=>setPostcode(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")checkPostcode()}}/><button onClick={checkPostcode}>Check <ArrowRight size={17}/></button></div>{checkedPostcode&&<><p className="slot-intro">Sample windows for {checkedPostcode}</p><div className="slots">{slots.map(s=><button key={s} className={slot===s?"picked":""} onClick={()=>setSlot(s)}>{s}</button>)}</div><small>Preview only. Choosing a slot here does not reserve it.</small></>}</div></section></>}
 </main><footer><div><span className="footer-brand">Franklin's<span>.</span></span><p>Good things for small people.<br/>A fresh way to shop, repeat and hire.</p></div><div><b>Explore</b><button onClick={()=>selectSection("shop")}>Shop all</button><button onClick={()=>selectSection("repeat")}>Repeat & top up</button><button onClick={()=>selectSection("hire")}>Prams & car seats</button></div><div><b>About this concept</b><p>Demonstration site. Products, prices, availability and delivery windows are illustrative. No purchases are processed.</p></div><small>Baby Supplies Business Mock-up · Concept Two</small></footer>
 <Sheet open={bagOpen} onOpenChange={setBagOpen}><SheetContent className="basket-sheet"><SheetHeader><SheetTitle>Your basket <span>({count})</span></SheetTitle><SheetDescription>Check your one-off, repeat and hire selections.</SheetDescription></SheetHeader>{lines.length?<><div className="basket-lines">{lines.map((line,i)=>{const p=items.find(x=>x.id===line.id)!;return <div className="basket-line" key={`${p.id}-${line.mode}-${line.weeks}-${line.months}`}><ProductImage tile={p.tile} name={p.name}/><div><strong>{p.name}</strong><small>{line.mode==="repeat"?`Every ${line.weeks} weeks`:line.mode==="hire"?`${line.months}-month hire${line.startDate?` · from ${line.startDate}`:" · choose a start date"}`:"One-off"}</small><div className="qty"><button onClick={()=>change(i,-1)} aria-label={`Reduce ${p.name}`}><Minus size={14}/></button>{line.quantity}<button onClick={()=>change(i,1)} aria-label={`Increase ${p.name}`}><Plus size={14}/></button></div></div><b>{money(p.price*line.quantity)}</b></div>})}</div><div className="basket-summary"><div><span>Indicative first charge</span><strong>{money(total)}</strong></div><p>Hire shows a monthly rate and repeat products show one delivery's price. Delivery fees, deposits and future charges are not included.</p><button onClick={()=>{setBagOpen(false);setOrderPlaced(false);setCheckoutOpen(true)}}>Review sample order <ArrowRight size={18}/></button></div></>:<div className="basket-empty"><ShoppingBasket size={38}/><h3>Your basket is waiting.</h3><p>There are little things worth getting ready for.</p><button onClick={()=>setBagOpen(false)}>Keep shopping <ArrowRight size={17}/></button></div>}</SheetContent></Sheet>
 <Dialog open={!!product} onOpenChange={open=>{if(!open)setProduct(null)}}><DialogContent className="product-dialog">{product&&<><div className={`detail-image image-tone-${product.tile%4}`}><ProductImage tile={product.tile} name={product.name}/></div><div className="detail-panel"><DialogHeader><p className="kicker">{product.brand.toUpperCase()} · {product.sku}</p><DialogTitle>{product.name}</DialogTitle><DialogDescription>{product.unit} · {product.stage}</DialogDescription></DialogHeader><strong className="detail-price">{money(product.price)} <small>{product.isHire?"/month":product.perUnit}</small></strong><p className="detail-description">{product.details}</p><div className="option-label">HOW WOULD YOU LIKE IT?</div>{product.isHire?<><div className="choice selected-choice"><span>Monthly hire</span><b>{money(product.price)}/month</b></div><label className="term-select">Preferred start date <input type="date" min={new Date().toISOString().slice(0,10)} value={hireStart} onChange={e=>setHireStart(e.target.value)}/></label><label className="term-select">Initial term <select value={months} onChange={e=>setMonths(Number(e.target.value))}><option value={1}>1 month</option><option value={3}>3 months</option><option value={6}>6 months</option></select></label><p className="detail-fine">Indicative term total: {money(product.price*months)} before deposit, delivery and returns. Date is a preference, not a reserved asset. Inspection and fitting arrangements need confirmation.</p></>:<><button className={mode==="once"?"choice selected-choice":"choice"} onClick={()=>setMode("once")}><span>Buy once</span><b>{money(product.price)}</b></button><button className={mode==="repeat"?"choice selected-choice":"choice"} onClick={()=>setMode("repeat")}><span>Set to repeat</span><b>Flexible delivery</b></button>{mode==="repeat"&&<label className="term-select">Deliver <select value={weeks} onChange={e=>setWeeks(Number(e.target.value))}><option value={2}>Every 2 weeks</option><option value={4}>Every 4 weeks</option><option value={6}>Every 6 weeks</option></select></label>}</>}<button className="detail-add" onClick={()=>add(product)}>{product.isHire?"Add hire plan to basket":"Add to basket"} <Plus size={19}/></button></div></>}</DialogContent></Dialog>
 <Dialog open={checkoutOpen} onOpenChange={setCheckoutOpen}><DialogContent className="checkout-dialog"><DialogHeader><p className="kicker">SAMPLE CHECKOUT</p><DialogTitle>{orderPlaced?"Your sample order is ready.":"Review your basket"}</DialogTitle><DialogDescription>{orderPlaced?`Sample window: ${slot}. No payment was taken and no order was sent.`:"This demonstrates the review step; live checkout is not connected."}</DialogDescription></DialogHeader>{!orderPlaced?<><div className="checkout-rows">{lines.map((x,i)=>{const p=items.find(y=>y.id===x.id)!;return <div key={i}><span>{p.name} × {x.quantity} <small>({x.mode==="repeat"?`every ${x.weeks} weeks`:x.mode==="hire"?`${x.months} month hire${x.startDate?` from ${x.startDate}`:""}`:"one-off"})</small></span><b>{money(p.price*x.quantity)}</b></div>})}<div><strong>Indicative first charge</strong><strong>{money(total)}</strong></div></div><label className="checkout-slot">Delivery preview <select value={slot} onChange={e=>setSlot(e.target.value)}><option value="">Choose a sample window</option>{slots.map(s=><option key={s}>{s}</option>)}</select></label><p className="detail-fine">Chosen sample window: {slot||"none yet"}. This is a preview, with no payment, stock reservation or fulfilment connection.</p><button className="detail-add" disabled={!slot} onClick={()=>{setOrderPlaced(true);setLines([])}}>Complete sample order <ArrowRight size={18}/></button></>:<button className="detail-add" onClick={()=>{setCheckoutOpen(false);setOrderPlaced(false)}}>Back to the shop <ArrowRight size={18}/></button>}</DialogContent></Dialog>
 {toast&&<div className="toast" role="status">{toast}<button onClick={()=>setToast("")} aria-label="Dismiss notification"><X size={15}/></button></div>}
 </div>
}
